apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-app-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-app-role
subjects:
- kind: ServiceAccount
  name: kube-app-sa
  namespace: default
